name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  backend:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main
    with:
      working_directory: backend
      tag_prefix: backend/v
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
